// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 FlyDSL Project Contributors
//
// Preprocessor utility for iterating over DSL backends.
// Adapted from Triton (python/src/main.cc).
//
// Usage:
//   // FLYDSL_BACKEND_COUNT and FLYDSL_BACKEND_0..N-1 are defined by CMake.
//   #define MY_ACTION(name) void do_##name();
//   FLYDSL_FOR_EACH_BACKEND(MY_ACTION)
//   // expands to: void do_rocdl();

#ifndef FLYDSL_BACKEND_BACKEND_H
#define FLYDSL_BACKEND_BACKEND_H

#ifndef FLYDSL_BACKEND_COUNT
#error "FLYDSL_BACKEND_COUNT must be defined by cmake/FlyDSLBackends.cmake."
#endif

#define FLYDSL_BACKEND_DETAIL_CONCAT(x, y) FLYDSL_BACKEND_DETAIL_CONCAT_IMPL(x, y)
#define FLYDSL_BACKEND_DETAIL_CONCAT_IMPL(x, y) x##y

#define FLYDSL_BACKEND_DETAIL_APPLY(MACRO, NAME) MACRO(NAME)

// clang-format off
#define FLYDSL_FOR_EACH_BACKEND_1(MACRO) FLYDSL_BACKEND_DETAIL_APPLY(MACRO, FLYDSL_BACKEND_0)
#define FLYDSL_FOR_EACH_BACKEND_2(MACRO) FLYDSL_FOR_EACH_BACKEND_1(MACRO) FLYDSL_BACKEND_DETAIL_APPLY(MACRO, FLYDSL_BACKEND_1)
#define FLYDSL_FOR_EACH_BACKEND_3(MACRO) FLYDSL_FOR_EACH_BACKEND_2(MACRO) FLYDSL_BACKEND_DETAIL_APPLY(MACRO, FLYDSL_BACKEND_2)
#define FLYDSL_FOR_EACH_BACKEND_4(MACRO) FLYDSL_FOR_EACH_BACKEND_3(MACRO) FLYDSL_BACKEND_DETAIL_APPLY(MACRO, FLYDSL_BACKEND_3)
#define FLYDSL_FOR_EACH_BACKEND_5(MACRO) FLYDSL_FOR_EACH_BACKEND_4(MACRO) FLYDSL_BACKEND_DETAIL_APPLY(MACRO, FLYDSL_BACKEND_4)

#define FLYDSL_FOR_EACH_BACKEND(MACRO) FLYDSL_BACKEND_DETAIL_CONCAT(FLYDSL_FOR_EACH_BACKEND_, FLYDSL_BACKEND_COUNT)(MACRO)
// clang-format on

#endif // FLYDSL_BACKEND_BACKEND_H
